version: '3.8'

services:
  modules-updater:
    container_name: kenyaemr-modules-updater
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./repos:/app/repos
      - ./modules:/app/modules
      - ./error_logs.txt:/app/error_logs.txt
      - ./modules.xlsx:/app/modules.xlsx
    tty: true
    stdin_open: true